### ISSUE TITLE
`to_string_no_chksum` returns debug representation instead of the descriptor string without the checksum?

### ISSUE THREAD

**Issue by RCasatta** [ElementsProject/elements-miniscript#85] opened 2024-06-14 08:21 UTC
https://github.com/ElementsProject/elements-miniscript/blob/9425f2e699418f549ac73c5042a6a9bebfb038e8/src/descriptor/mod.rs#L438

**Comment by apoelstra** [comment] 2024-06-14 13:16
Dupe of https://github.com/ElementsProject/elements-miniscript/issues/34 ... but I could have sworn I fixed this. Thanks for the poke. I will investigate.

**Closed** 2024-09-24 16:04 UTC
